
# VARIABLES
SQLITE_RELEASE_YEAR=2023
SQLITE_VERSION=3420000

# DOWNLOAD (https://www.sqlite.org/download.html)
wget http://sqlite.org/$SQLITE_RELEASE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip
unzip sqlite-amalgamation-$SQLITE_VERSION.zip
mv sqlite-amalgamation-$SQLITE_VERSION sqlite

# BUILD LINUX (x86)
gcc -DHAVE_READLINE -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_HAVE_ZLIB -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_THREADSAFE=0 -DUSE_URI sqlite/shell.c sqlite/sqlite3.c -o sqlite3-linux-x86 -ldl -lz -lm -lreadline -lncurses -O3
chmod +x sqlite3-linux-x86

# BUILD LINUX (arm64)
#TODO: Use github actions for this also, somehow

# BUILD MACOS (x86)
gcc -DHAVE_READLINE -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_HAVE_ZLIB -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_THREADSAFE=0 -DUSE_URI sqlite/shell.c sqlite/sqlite3.c -o sqlite3-darwin-x86 -target x86_64-apple-macos10.12 -ldl -lz -lm -lreadline -lncurses -O3
chmod +x sqlite3-darwin-x86

# BUILD MACOS (arm64)
gcc -DHAVE_READLINE -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_HAVE_ZLIB -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_THREADSAFE=0 -DUSE_URI sqlite/shell.c sqlite/sqlite3.c -o sqlite3-darwin-arm -target arm64-apple-macos11 -ldl -lz -lm -lreadline -lncurses -O3
chmod +x sqlite3-darwin-arm

# BUILD MACOS (universal)
lipo -create -output sqlite3-darwin-universal sqlite3-darwin-x86 sqlite3-darwin-arm
chmod +x sqlite3-darwin-universal

# BUILD WIN32 (x86)
gcc -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_THREADSAFE=0 -DUSE_URI -I. sqlite/shell.c sqlite/sqlite3.c -o sqlite3-win32-x86.exe -O3
chmod +x sqlite3-win32-x86.exe

# BUILD WIN32 (arm64)
#TODO: Use github actions for this also, somehow

# CLEANUP
rm sqlite-amalgamation-$SQLITE_VERSION.zip
rm -rf sqlite
